### ISSUE TITLE
hotel_offers_by_hotel not working properly

### ISSUE THREAD

**Issue by nans64** [amadeus4dev-examples/amadeus-ruby#40]
## Description

I am trying to use `amadeus.shopping.hotel_offers_by_hotel.get(hotelId: "RWPARRCR")`
The response is positive the the result is always empty.
I tried with different hotel ID maybe I am missing something out there...
## Steps to Reproduce

1. `amadeus.shopping.hotel_offers_by_hotel.get(hotelId: "RWPARRCR")`
2. `=> #<Amadeus::Response:0x00005602d532ae78 @http_response=#<Net::HTTPOK 200 OK readbody=true>, @request=#<Amadeus::Request:0x00005602d534b600 @host="api.amadeus.com", @port=443, @ssl=true, @scheme="https", @verb=:GET, @path="/v2/shopping/hotel-offers/by-hotel", @params={:hotelId=>"RWPARRCR"}, @bearer_token="Bearer i0q0KquqTF5EYsauqdIhQ6rqXRo8", @client_version="3.3.0", @language_version="2.5.1", @app_id=nil, @app_version=nil, @headers={"User-Agent"=>"amadeus-ruby/3.3.0 ruby/2.5.1", "Accept"=>"application/json, application/vnd.amadeus+json", "Authorization"=>"Bearer i0q0KquqTF5EYsauqdIhQ6rqXRo8"}, @http_request=#<Net::HTTP::Get GET>>, @status_code=200, @parsed=true, @body="{}", @result={}, @data=nil>
`

__Expected Behavior: I should get the list of the rooms that are available

__Actual Behavior: I get an empty answer 

__Stable Behavior? 100%

## Versions

[What version of Ruby/Rubygems are you running? What Operating System are you on?]
2.5.1
## Checklist

Please make sure you checked the following:

* Are you running Ruby 2.2+? Yes 
* Did you download the latest version of this gem? 3.3.0

**Comment by alnacle** [comment]
Thanks for reporting this! Seems to be a problem in our backend. We are already working on it to fix it.

**Comment by tsolakoua** [comment]
The Hotel Search v2 will be decommissioned soon and Hotel Search v3 is already live, so I close the issue
